name: aandi_tech_blog
description: Tech blog APIs package for AANDI admin service
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  aandi_api_endpoints:
    path: ../aandi_api_endpoints
  dio: ^5.9.0

dev_dependencies:
  lints: ^6.0.0
  flutter_test:
    sdk: flutter
